freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: pkg install -y
        meson ninja pkgconf python2
  script:
      - meson builddir --warnlevel 3 --buildtype release
      - ninja -v -C builddir
