.\"                                      Hey, EMACS: -*- nroff -*-
.TH GARMIN-FORERUNNER-TOOLS 1 "March 31, 2008"
.SH NAME
garmin_gpx \- convert .gmn files into TrainingDatabase XML data for upload
to various activity tracking websites.
.SH SYNOPSIS
.B garmin_tcx
.I file
.PP
\fBgarmin_tcx\fP reads a .gmp file as produced by \fBgarmin_save_runs\fP, and
writes to standard output the xml representation.
.SH SEE ALSO
.BR garmin_get_info (1),
.BR garmin_save_runs (1),
.BR garmin_dump (1).
.br
.SH AUTHOR
garmin_tcx was written by Jens Georg.
